name: Android Production Build

# Production builds triggered manually only
on:
  workflow_dispatch:

jobs:
  build_android_production:
    name: Build Android Production
    type: build
    params:
      platform: android
      profile: production
      auto_submit: false
